import { SignIn, SignInButton, SignOutButton, useAuth } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import { api } from "~/utils/api";

const Home: NextPage = () => {
  const { data } = api.posts.getAll.useQuery();

  console.log(data);

  const user = useAuth();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <h1 className="text-4xl font-bold text-white">
            Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
          {user.isSignedIn ? (
            <div>
              <p className="text-white">You are signed in!</p>
              <SignOutButton />
            </div>
            ) : (
            <div>
                <p className="text-white">You are not signed in</p>
          <SignInButton>
            <button>Sign in with Clerk</button>
          </SignInButton>
        </div>
        )}
        <div>
          {data?.map((post) => (
            <div key={post.id}>
                <p>{post.content}</p>
        </div>
        ))}
        </div>
      </main>
    </>
  );
};

export default Home;
