import { type NextPage } from "next";
import Head from "next/head";
const SinglePostView: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen justify-center justify-center">
        <div className="w-full md:max-w-2xl border-slate-100 border-x h-full">
          <div className="border-b border-slate-100 p-4">
            <div>
             Post View
            </div>
          </div>
        </div>
      </main>
    </>
  );
};

export default SinglePostView;
